### ISSUE TITLE
Can jpeg-archive replace files?

### ISSUE THREAD

**Issue by donaldallen** [danielgtaylor/jpeg-archive#15]
Whenever I run jpeg-archive, it puts everything into a Comp folder. Is there a way to have it replace the images it's recompressing?

**Comment by danielgtaylor** [comment]
@donaldallen not at the moment. This is by design to make it very hard to delete the original files accidentally, especially if you aren't happy with the output. I'm not opposed to adding some kind of opt-in, but the default should always be to make a separate copy.

**Comment by CoolOppo** [comment]
It's really not a good idea at all.

**Comment by javabean** [comment]
AFAIK, you can always ``jpeg-recompress -c image.jpg image.jpg`` which will happily overwrite your file with the optimized version.
