### ISSUE TITLE
Error while compiling jpeg-archive

### ISSUE THREAD

**Issue by nikitsaraf** [danielgtaylor/jpeg-archive#21]
I am trying to build jpeg-archive on Mac OS X Yosemite 10.10.2, and it is throwing me the following error.

```
cc -std=c99 -Wall -O3 -I/opt/mozjpeg/include -c -o src/util.o src/util.c
src/util.c:133:13: warning: implicit declaration of function 'jpeg_c_bool_param_supported' is invalid in C99 [-Wimplicit-function-declaration]
        if (jpeg_c_bool_param_supported(&cinfo, JBOOLEAN_OPTIMIZE_SCANS)) {
            ^
src/util.c:133:49: error: use of undeclared identifier 'JBOOLEAN_OPTIMIZE_SCANS'
        if (jpeg_c_bool_param_supported(&cinfo, JBOOLEAN_OPTIMIZE_SCANS)) {
                                                ^
src/util.c:134:13: warning: implicit declaration of function 'jpeg_c_set_bool_param' is invalid in C99 [-Wimplicit-function-declaration]
            jpeg_c_set_bool_param(&cinfo, JBOOLEAN_OPTIMIZE_SCANS, FALSE);
            ^
src/util.c:134:43: error: use of undeclared identifier 'JBOOLEAN_OPTIMIZE_SCANS'
            jpeg_c_set_bool_param(&cinfo, JBOOLEAN_OPTIMIZE_SCANS, FALSE);
                                          ^
2 warnings and 2 errors generated.
make: *** [src/util.o] Error 1
```
Any ideas, may I missing any dependency ?

**Comment by danielgtaylor** [comment]
@nikitsaraf please update homebrew (`brew update` if you are using it) and install the latest Mozjpeg, then try this again. You'll need at least Mozjpeg 3.0 now!

**Comment by clns** [comment]
If you've installed mozjpeg with Homebrew, then the [MOZJPEG_PREFIX](https://github.com/danielgtaylor/jpeg-archive/blob/master/Makefile#L6) used in the Makefile is not correct. Homebrew installs it in `/usr/local/opt/mozjpeg`. If so, you can [modify your Makefile](https://github.com/clns/jpeg-archive/commit/e1af352aa890a03ec41dceb0446c26c0454bbb90) or export MOZJPEG_PREFIX with the correct value.

@danielgtaylor I didn't send a pull request as this is an easy change and I don't know either how it relates to linux.

**Comment by danielgtaylor** [comment]
I've gone ahead and updated the default location to point to where Homebrew installs it in f1d2864. Please reopen the issue if you still have problems!
