### ISSUE TITLE
Improvement: parallel folder compression

### ISSUE THREAD

**Issue by javabean** [danielgtaylor/jpeg-archive#39]
Hi,

I enhanced your jpeg-archive script to be usable without any 3rd-party dependencies, and in-place compress either a single file or a whole folder (keeping all files meta-data).

You may want to include it in the project distribution (for which I of course grant you all rights):
https://gist.github.com/javabean/9ef827ea82268c1a9868ec617de3a1d8

**Comment by lfos** [comment]
Thanks for writing this script, it might be helpful to people who do not have access to Ladon or GNU Parallel (the jpeg-archive script now supports both of them). I do not think reinventing the wheel and having something with less dependencies is worth the additional maintenance burden in mainline, though. Closing this and keeping it as a reference for people looking for such a script in the future :)
