### ISSUE TITLE
Generic image-compare

### ISSUE THREAD

**Issue by sinconix** [danielgtaylor/jpeg-archive#42]
Please consider allowing jpeg-compare to take two (instead of one) uncompressed PPM images.
This would make it much more flexible and for comparing other image compressors.

**Comment by lfos** [comment]
Both arguments to jpeg-compare can now be PPMs and, even better, jpeg-compare now auto-detects file types. So you can simply call `jpeg-compare 1.ppm 2.ppm` without any further options.
