### ISSUE TITLE
Adding PPM export to JPEG-recomrpess

### ISSUE THREAD

**Issue by maadjordan** [danielgtaylor/jpeg-archive#43]
Please allow for export in PPM to allow using the matrix methods on different formats (JP2 or others)..

**Comment by lfos** [comment]
Not sure. The main purpose of jpeg-recompress is to recompress the input as a JPEG with given quality constraints... We cannot use another output format (especially not a lossless format) for this.

**Comment by maadjordan** [comment]
The aim is to open the provided methods to other formats. It will be a step in the direction of video support

**Comment by lfos** [comment]
I still do not understand. The purpose of jpeg-recompress is to find the optimal compression ratio (such that the resulting image is as small as possbile without sacrificing visual quality). How can this possibly work with a lossless image format?

**Comment by maadjordan** [comment]
Beamr has brought jpeg-mini method from still jpeg image to video. if smallfry can be added to FFmpeg as filter to would help in producing a smaller video files. I've roughly tested jpeg-recompress on video files with mjpeg compression (its frames are jpeg without the huff coef header). I've added example file
[MJPEG_sample.zip](https://github.com/danielgtaylor/jpeg-archive/files/1670133/MJPEG_sample.zip)
.

**Comment by lfos** [comment]
Extending to videos makes sense. Extending to a lossless image output format (such as PPM) does not.
