### ISSUE TITLE
Segfaults in jpeg-compare

### ISSUE THREAD

**Issue by dmak** [danielgtaylor/jpeg-archive#49]
Two test cases:
- `jpeg-compare right_move_bg.jpg right_move_bg.jpg`
`Segmentation fault`
Download: [right_move_bg.jpg](https://www.dropbox.com/s/0t8ueagi1imp7il/right_move_bg.jpg?dl=1)

- `jpeg-compare line.jpg line.jpg`
 `*** Error in jpeg-compare: free(): invalid pointer: 0x8055b220 ***`
`======= Backtrace: =========`
`/lib/i386-linux-gnu/libc.so.6(+0x6929b)[0xb761429b]`
`/lib/i386-linux-gnu/libc.so.6(+0x6f527)[0xb761a527]`
`/lib/i386-linux-gnu/libc.so.6(+0x6fcd1)[0xb761acd1]`
`jpeg-compare(+0x293b)[0x8009693b]`
`jpeg-compare(+0x17f4)[0x800957f4]`
`jpeg-compare(main+0x14a)[0x8009555a]`
`/lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf7)[0xb75c3517]`
`jpeg-compare(+0x15a5)[0x800955a5]`
`Aborted`
Download: [line.jpg](https://www.dropbox.com/s/xi22wi0dk2tzffw/line.jpg?dl=1)

**Comment by lfos** [comment]
Fixed in commit 7ef223e (Fix computation of buffer sizes, 2017-11-29).
