### ISSUE TITLE
Can jpeg-archive compress file from buffer?

### ISSUE THREAD

**Issue by elisoncampos** [danielgtaylor/jpeg-archive#52]
Is it possible to compress a file that is not written to the disk? Like, use it in an AWS lambda process so I could compress uploaded files? When you download a file from S3 to use it in lambda all i have is their buffer. I could write it to disk, then compress and upload but that would add processing time that could be saved.

thanks in advance.

**Comment by javabean** [comment]
Reading from the source code, I believe current version requires a file on disk.
Have you tried to "stream" your memory buffer through a UNIX FIFO pipe (`man mkfifo`), and using that as an input "file"?

**Comment by lfos** [comment]
Fixed in 76b1868 (Only read input once, 2018-03-14).
