### ISSUE TITLE
How can I use ladon or jpeg-archive in windows?

### ISSUE THREAD

**Issue by xberg** [danielgtaylor/jpeg-archive#57]
Hi,
I was unable to find a ladon or a jpeg-archive windows executable. Could you please kindly add the instructions so that I can execute your very promising jpeg-recompress on multiple recursive JPG in windows? 
I saw a while a ago one of your users proposed a branch to allow recursive processing directly in jpeg-recompress: was this never adopted?
thanks and keep up the good work!

**Comment by javabean** [comment]
Not sure about this (I haven't tested), but you may have some success by using my wrapper in Cygwin (or equivalent): https://gist.github.com/javabean/9ef827ea82268c1a9868ec617de3a1d8
You may have to adjust the autogestion of the number of CPU cores, but it should otherwise work as-is.

**Comment by lfos** [comment]
Not sure about Windows but jpeg-archive now also supports GNU Parallel. Closing this for now...

**Comment by c33s** [comment]
posting this as reference. i also have problems with ladon on windows. 
```
ladon --verbose "*" -- echo asdf
Processing 0 files...
```
it looks like the glob does not work.

as alternative to ladon there is rush: https://github.com/shenwei356/rush

```
find *.JPG | rush "jpeg-recompress -m smallfry {} {}.new.jpg"
```

**Comment by c33s** [comment]
also see https://github.com/danielgtaylor/ladon/issues/9
