### ISSUE TITLE
Rough Debian packaging

### ISSUE THREAD

**Issue by szepeviktor** [danielgtaylor/jpeg-archive#66]
~~Today I've make this script.
https://github.com/szepeviktor/debian-server-tools/blob/master/package/jpeg-archive-jessie.sh#L13-L16~~

*I am not satisfied with kind of packaging.*

**Comment by szepeviktor** [comment]
Available here: http://szepeviktor.github.io/

**Comment by szepeviktor** [comment]
https://github.com/szepeviktor/debian-server-tools/blob/master/package/docker-backport-jpeg-archive.sh

This script builds mozjpeg separately but in the same container, then packages jpeg-archive.

**Comment by lfos** [comment]
What's this ticket about, though?

Maybe you can upload your script to Docker Hub or something?

**Comment by szepeviktor** [comment]
@lfos I was planning to add my /debian dir to this repo:
https://github.com/szepeviktor/debian-server-tools/tree/master/package/jpeg-archive/debian

**Comment by szepeviktor** [comment]
@lfos Excuse me, I mean add it to the jpeg-archive repo.

**Comment by szepeviktor** [comment]
This is the script that does it all:
https://github.com/szepeviktor/debian-server-tools/blob/master/package/docker-backport-jpeg-archive.sh

**Comment by lfos** [comment]
Not sure. What is the benefit of having it in the jpeg-archive repo?

**Comment by szepeviktor** [comment]
Anyone could build the package!
