### ISSUE TITLE
min can be larger than max in jpeg-recompress

### ISSUE THREAD

**Issue by mika-s** [danielgtaylor/jpeg-archive#74]
I'm not sure if this really is an issue or not.

The `min ` argument is allowed to be larger than the `max` argument. jpeg-recompress will run like this:

**jpeg-recompress.exe original.jpg new.jpg  --quality low --max 10**
```
Metadata size is 0kb
ssim at q=25 (40 - 10): 0.992004
ssim at q=18 (26 - 10): 0.985314
ssim at q=15 (19 - 10): 0.979637
ssim at q=13 (16 - 10): 0.973997
ssim at q=12 (14 - 10): 0.969485
Final optimized ssim at q=12: 0.963419
New size is 5% of original (saved 1327 kb)
```

**Comment by lfos** [comment]
Fixed in 68dcd25 (Ensure minimum quality is smaller than maximum quality, 2018-05-20).
