### ISSUE TITLE
jpeg-recompress can pick a JPEG quality larger than max

### ISSUE THREAD

**Issue by mika-s** [danielgtaylor/jpeg-archive#75]
jpeg-recompress will usually pick JPEG quality values that are far from the `min` and `max` edges. However, in many cases, the quality converges towards `max` because `max` is small and the metric is smaller than the target. This will cause `min` to increase to a larger value than `max` and the final JPEG quality is higher than `max`. Take, for instance, [this](https://i.imgur.com/50VwRNE.jpg) image.

**jpeg-recompress.exe original.jpg new.jpg  --quality low --min 1 --max 5**

```
Metadata size is 0kb
ssim at q=3 (1 - 5): 0.851791
ssim at q=4 (4 - 5): 0.877762
ssim at q=5 (5 - 5): 0.899344
ssim at q=6 (6 - 5): 0.919418
ssim at q=6 (7 - 5): 0.919418
Final optimized ssim at q=6: 0.911516
New size is 3% of original (saved 1360 kb)
```

Not sure if can be considered wrong, but I still wanted to mention it.

**Comment by lfos** [comment]
Fixed in 92a69ec (Ensure the quality stays within the given bounds, 2018-05-20).
