### ISSUE TITLE
Adding support for larger files

### ISSUE THREAD

**Issue by maadjordan** [danielgtaylor/jpeg-archive#77]
I've tested latest built (2018_01_18) on jpegmini sample file from blog.jpegmini.com/jpegmini-pro-for-windows-can-now-optimize-photos-up-to-128mp/

the built has failed. please check it

**Comment by lfos** [comment]
What do you mean by "the built has failed"? Please provide more information.

**Comment by maadjordan** [comment]
sorry its my mistake. i used wrong commands. the result is:

original: 70,390,888 bytes
jp-reco: 18,955,051 bytes
jp-mini:  32,323,908 bytes
