### ISSUE TITLE
An inquiry about the maximum size a jpeg-recompress image

### ISSUE THREAD

**Issue by amughrabi** [danielgtaylor/jpeg-archive#79]
I wish to have an answer about the maximum pixel dimensions of a jpeg-recompress image; for instance, what is the maximum image width and height (W x H) for the source image before calling it via command line? 

Please note that [Mozjpeg](https://github.com/mozilla/mozjpeg/issues/277) defined it as 65500x65500 pixels. Could you please confirm if jpeg-recompress has the same pixel dimensions? if not, could you please provide the maximum pixel dimensions?

Thanks

**Comment by lfos** [comment]
I do not think we have any explicit limits, other than the mozjpeg limit and obvious limits imposed by the environment (e.g. memory limits).

**Comment by amughrabi** [comment]
Thanks, @lfos!
