### ISSUE TITLE
Lib location should be /opt/mozjpeg/lib64 on 64 bit ubuntu

### ISSUE THREAD

**Issue by stuaxo** [danielgtaylor/jpeg-archive#89]
Editing the makefile makes this compile on 64 bit ubuntu

**Comment by lfos** [comment]
You can set `MOZJPEG_PREFIX` when running make(1). No need to edit the Makefile.

**Comment by stuaxo** [comment]
I don't think that would work as it appends /lib to the location, but the library is in lib64.

64 bit debian and ubuntu are fairly popular distros, is there any chance the location could be supported out of the box?
